### ISSUE TITLE
Astro binding: thing remains in INITIALIZING state

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab2-addons#1179]
Often at startup my astro thing remains in INITIALIZING state.
No error in logs.
Hint: code in initialize() that takes too much time ?
##

**Comment by lolodomo** [comment]
I really see nothing in the code that could explain the problem !

**Comment by sutyagin** [comment]
I have the same issue.

**Comment by lolodomo** [comment]
Strangely after recompiling the binding with additional debug logs, I am now not able to reproduce the issue ! The problem is probably not obvious.

**Comment by lopez1de** [comment]
Any news on this? I have this problem too. Sometimes it isn't initialized.

**Comment by kaikreuzer** [comment]
I would expect it to be fixed on the recent snapshots.
Can you confirm that you are testing on such a version?

**Comment by lopez1de** [comment]
Kai,

I'm on 1.8.3. Got it via apt-get upgrade. I think this is a stable release. If you say "snapshots", you mean something like a beta pre stable build or something? How do I get those?

2016-12-09 23:14:56.407 [INFO ] [.o.core.internal.CoreActivator] - openHAB runtime has been started (v1.8.3).

**Comment by kaikreuzer** [comment]
Then you are completely wrong here in this issue. There isn't anything like an "astro thing" and an INITIALIZING status in openHAB 1 - this issue is purely about openHAB 2.

**Comment by kaikreuzer** [comment]
@lolodomo With the recent ESH fixes, could you confirm that this issue is fixed now?

**Comment by lopez1de** [comment]
>Then you are completely wrong here in this issue. There isn't anything like an "astro thing" and an INITIALIZING status in openHAB 1 - this issue is purely about openHAB 2.
 
Sorry. Sort of same issue, but wrong version.

**Comment by lolodomo** [comment]
@kaikreuzer : if you mean with snapshot 633 or later, no I have not yet tested. I am still running the snapshot 627.
With this snapshot, I am not sure I encountered the problem, maybe, maybe not, I don't remember exactly. If it is still hapening with this snapshot, that is certainly less frequently than before.
If it does not happen anymore after a reasonable number of restarts, I will let you know and it will be the time to close the issue. Too early I think.

**Comment by lolodomo** [comment]
@kaikreuzer : I just reproduced it with the snapshot 636. So yes, unfortunately, this issue is still relevant.
```
openhab> smarthome:things
ntp:ntp:local (Type=Thing, Status=ONLINE, Label=NTP, Bridge=null)
astro:sun:local (Type=Thing, Status=INITIALIZING, Label=Astro, Bridge=null)
...
```

**Comment by lolodomo** [comment]
I close this issue as the problem did not occur again since a certain time.
