### ISSUE TITLE
Homematic No variables loaded at gateway-extras

### ISSUE THREAD

**Issue by McLive** [openhab/openhab2-addons#2223]
I'm running openHAB 2 on my raspberry pi and added the GATEWAY-EXTRAS thing but it doesn't load any variables from my CCU1.

This is my trace log:
https://pastebin.com/LYuRsxp5

This is how it looks like:
![GATEWAY-EXTRAS](http://img.mclive.eu/20170430170928.png)

This came up from adding the gateway-extras thing:
https://pastebin.com/yrrFeaRm

**Comment by MHerbst** [comment]
Are you using the release version of the binding? I remember that there have been some fixes regarding GATEWAY-EXTRAS since the release version. 
Can you try it with the latest snapshot build or the latest PR build (https://community.openhab.org/t/frequently-asked-questions-faqs/17727#addons)?

**Comment by McLive** [comment]
I'm currently running "binding-homematic - 2.0.0" installed from PaperUI.

I'll try the latest PR build now

**Comment by McLive** [comment]
After installing the latest snapshot build of the binding and setting the Gateway Type to "CCU", all variables are now loaded.

Thank you! :+1:

**Comment by MHerbst** [comment]
Good to hear :-) Can you please close this issue.

**Comment by McLive** [comment]
It looks like this updated created another issue. :(
After starting openHAB, my CCU1 crashes. ("Eine Komponente der Zentrale reagiert nicht mehr" o.ä.). This didn't happened before. 

Because of the connection lost, I'm getting these errors:
https://pastebin.com/z5arE67C

**Comment by MHerbst** [comment]
That's strange. Are you maybe trying to connect from two different openHAB instances at the same time to the CCU? With the CCU2 I get problems when I connect two openHAB instances with Homematic.

**Comment by McLive** [comment]
No, I only have one installed on my raspbery PI.

**Comment by MHerbst** [comment]
Can you check the CCU log file? Maybe there is an error message that can help us to find the reason.

**Comment by McLive** [comment]
Is /var/log/messages the right log?
This is the content of it:
https://pastebin.com/JVA9ChAb

**Comment by McLive** [comment]
I just googled some of these errors and it seems that it is triggered by openHAB not answering on XML-RPC events/requests.
I guess thats a problem with the snapshot build I installed :(

**Comment by MHerbst** [comment]
Ich will try it tomorrow with my CCU. It's a CCU 2 so it may behave a bit different.  
I have checked your logs again but none of the shows the messages that are printed when the binding is started. Maybe there is a problem. The bridge configuration contains an option where you can explicitly set the gateway type that CCU. You should also check the port configuration.

**Comment by McLive** [comment]
Ok, this is my current bridge configuration:
![bridge](http://img.mclive.eu/20170504222951.png)

I haven't even changed them when updating from release to snapshot version of the binding except switching gateway type from "auto" to "ccu" to get the variables working with gateway-extras.

**Comment by MHerbst** [comment]
@gerrieg Do you have an idea why the CCU 1 has problems with the communication and crashes?

**Comment by gerrieg** [comment]
Not really, maybe it is to slow for all the rpc calls. You can try the latest snapshot (build 908). I completely refactored the RPC server part and also optimized metadata loading a little bit at a certain constellation. Maybe it helps, it has been merged yesterday.

I would like to ask you if you can send me a full startup TRACE log. The CCU1 autodetection does not seem to work, because you have to set the gateway from auto to ccu. With the log, i can fix the autodetection. Thanks!

**Comment by McLive** [comment]
Thanks so far, I'll be able to send a full startup TRACE log next weekend and will try the latest snapshot build.

**Comment by McLive** [comment]
@gerrieg 
I now installed build #915.
194 | Active   |  80 | 2.1.0.201705121229    | Homematic Binding                                      | org.openhab.binding.homematic

But again, this error showed up after starting openHAB:
[!http://img.mclive.eu/20170512194129.png]

This is the full trace log from starting openHAB:
http://krz.link/1Jm?secure=JDEb8lXOYZ4ePPmb&plain

**Comment by McLive** [comment]
I now updated CUxD from version 1.3 to 1.10 and haven't got that error again for now.

Maybe it works now

**Comment by McLive** [comment]
Well, got another one now:
![error](http://img.mclive.eu/20170512212026.png)

https://pastebin.com/z5jXkTt3

**Comment by gerrieg** [comment]
Based on your logfile, the problem seems to be CUxD. The binding sends the command rssiInfo() to the CUxD daemon and then the CCU does not answer anymore. The CCU also shows the error message in the WebGUI.
```
2017-05-12 19:40:02.597 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcRequest:
rssiInfo()

2017-05-12 19:40:02.601 [TRACE] [al.communicator.client.SocketHandler] - Returning socket for port 8701
2017-05-12 19:40:02.643 [DEBUG] [nal.communicator.client.BinRpcClient] - BinRpcMessage socket failure, sending message again 1/1
2017-05-12 19:40:02.644 [TRACE] [al.communicator.client.SocketHandler] - Closing Socket on port 8701
2017-05-12 19:40:02.647 [DEBUG] [ommunicator.AbstractHomematicGateway] - Loading values for channel HmChannel[number=0,type=MAINTENANCE,initialized=false] of device 'BidCoS-RF'
2017-05-12 19:40:02.663 [TRACE] [al.communicator.client.SocketHandler] - Creating new socket for port 8701
2017-05-12 19:40:02.668 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcResponse:
null
2017-05-12 19:40:02.671 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcResponse:
null
2017-05-12 19:40:02.674 [WARN ] [matic.handler.HomematicBridgeHandler] - Unable to load RSSI values from bridge 'fe7f373f'
2017-05-12 19:40:02.688 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcRequest:
getParamset()
BidCoS-RF:0
MASTER

2017-05-12 19:40:02.693 [TRACE] [al.communicator.client.SocketHandler] - Returning socket for port 2001
2017-05-12 19:40:02.690 [ERROR] [matic.handler.HomematicBridgeHandler] - Connection refused (Connection refused)
```
From the CUxD changelog, this should have been fixed with version 1.8a:

- Absturz  bei devconfig/rssi Abfrage aus der WebUI beseitigt

Please try this version of the binding: [Download ](https://drive.google.com/file/d/0Bw7zjCgsXYnHZ1BUYm9aNGQ5UEE/view?usp=sharing) 
I disabled the rssi call for CUxD in this version, you should see this warning in the logfile if the binding is active:
```
Testversion with rssi values disabled for CUxD
```

**Comment by McLive** [comment]
The CUxD error is gone after updating CUxD to version 1.10.
I'm now running your version, but I'm still getting errors:
![error](http://img.mclive.eu/20170513151148.png)

This is the trace log:
https://dr0p.it/AEsiKmam3R1PlW9OW5Q2nV5VfeGw

I really have no idea whats going on here..

**Comment by gerrieg** [comment]
In the new logfile, i can not see any binding related problem. The last event from the CCU is:
```
2017-05-13 15:05:08.880 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Boolean) value 'false' for 'LEQ0564104:2#LOWBAT' from gateway with id 'fe7f373f'
```

Then the binding sends only the heartbeat messages and 5 minutes later, the binding detects that no events are receiving anymore.
```
2017-05-13 15:10:31.771 [INFO ] [ommunicator.AbstractHomematicGateway] - No event since 322 seconds from gateway 'fe7f373f', restarting RPC server
```
Have unfortunately no idea what the problem can be, but i'm pretty sure it's the CCU and not the binding.

**Comment by McLive** [comment]
So this error is caused because the BidCos-RF crashed?

`2017-05-13 15:10:37.199 [ERROR] [ommunicator.AbstractHomematicGateway] - Unexpected readed size. current: 14472, excepted: 36969
java.io.IOException: Unexpected readed size. current: 14472, excepted: 36969
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:503)[30:org.apache.commons.io:2.2.0]
	at org.openhab.binding.homematic.internal.communicator.message.BinRpcMessage.<init>(BinRpcMessage.java:85)[197:org.openhab.binding.homematic:2.1.0.201705130723]
	at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:89)[197:org.openhab.binding.homematic:2.1.0.201705130723]
	at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:102)[197:org.openhab.binding.homematic:2.1.0.201705130723]
	at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:78)[197:org.openhab.binding.homematic:2.1.0.201705130723]
	at org.openhab.binding.homematic.internal.communicator.client.RpcClient.listDevices(RpcClient.java:140)[197:org.openhab.binding.homematic:2.1.0.201705130723]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.getDeviceDescriptions(AbstractHomematicGateway.java:448)[197:org.openhab.binding.homematic:2.1.0.201705130723]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.newDevices(AbstractHomematicGateway.java:682)[197:org.openhab.binding.homematic:2.1.0.201705130723]
	at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleNewDevice(RpcResponseHandler.java:101)[197:org.openhab.binding.homematic:2.1.0.201705130723]
	at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:52)[197:org.openhab.binding.homematic:2.1.0.201705130723]
	at org.openhab.binding.homematic.internal.communicator.server.BinRpcResponseHandler.run(BinRpcResponseHandler.java:46)[197:org.openhab.binding.homematic:2.1.0.201705130723]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]`

I'm wondering that I didn't had that problem some time back when I was using an older version of the binding and wasn't able to use the Gatway-Extras.

**Comment by gerrieg** [comment]
yes, because there is no answer anymore from the CCU to the rpc calls.

**Comment by McLive** [comment]
Ok, I'll try to update the CCU now. I'm currently running version 1.515.

**Comment by McLive** [comment]
After updating the CCU firmware, I haven't got that error anymore until now. 
I'll keep an eye on it.

Thank you for your help @MHerbst @gerrieg :+1:

**Comment by gerrieg** [comment]
great! 👍

**Comment by McLive** [comment]
Well, it just crashed again now.... :(

https://pastebin.com/Pnt35jSH

**Comment by McLive** [comment]
Some things I also tried now:

- Removing the Gateway-Extras Thing:
	Issue is not fixed, BidCos-RF still crashes

- Setting the CCU-Type back to "Auto":
	Issue seems fixed, BidCos-RF doesn't crash (running for around 4 hours now)

So it looks like there is an issue with the Gateway-Type setting at the HomeMatic Bridge.

**Comment by gerrieg** [comment]
The only difference between auto and ccu are the TCLRega scripts. If the binding detects a CCU (or you set the gatewayType to CCU), the binding executes some additional scripts at startup to fetch the variables, programs and device names. That's all. 
And these scripts return values, so i have still no idea why your CCU crashes.

Can you please once again post a full trace startup log (with gatewayType CCU) and wait until the ccu crashes. I'll dig again through the logfile.

**Comment by McLive** [comment]
Sure! :)
Here are the logs with Gateway-Type CCU
openhab.log: https://dr0p.it/APaxQTJ1sSvbi3YQVvDagBjNw23O
CCU Syslog: https://dr0p.it/ABocOteT9CcRRxs9sigaIuquZ0uI

**Comment by gerrieg** [comment]
Absolute no idea, the binding runs for about an hour, then the CCU stops sending events. The binding reconnects some times and after a while the CCU crashes.
Any chance for you to update to a CCU2? The CCU1 is pretty old and slow.

**Comment by McLive** [comment]
I guess that's the only way to fix it.

Thanks for your help tho ;)
