### ISSUE TITLE
[tesla] Runtime error in charge current

### ISSUE THREAD

**Issue by Rathna-K** [openhab/openhab2-addons#4230]
I believe one of the channels is having issue converting null as per the log. 

```
==> /var/log/openhab2/openhab.log <==
2018-11-15 15:13:36.810 [ERROR] [nternal.items.ItemStateConverterImpl] - A conversion of null was requested:
java.lang.IllegalArgumentException: State must not be null.
        at org.eclipse.smarthome.core.internal.items.ItemStateConverterImpl.convertToAcceptedState(ItemStateConverterImpl.java:52) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.sendUpdate(ProfileCallbackImpl.java:135) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onStateUpdateFromHandler(SystemDefaultProfile.java:54) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$9(CommunicationManager.java:477) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$11(CommunicationManager.java:497) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.handleCallFromHandler(CommunicationManager.java:493) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.stateUpdated(CommunicationManager.java:475) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$1.stateUpdated(ThingManagerImpl.java:167) ~[?:?]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:287) ~[?:?]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:306) ~[?:?]
        at org.openhab.binding.tesla.handler.TeslaHandler.parseAndUpdate(TeslaHandler.java:640) ~[?:?]
        at org.openhab.binding.tesla.handler.TeslaHandler$Request.run(TeslaHandler.java:1258) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
        at org.openhab.binding.tesla.internal.throttler.QueueChannelThrottler.lambda$0(QueueChannelThrottler.java:41) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]

==> /var/log/openhab2/events.log <==
```

**Comment by cguedel** [comment]
Can you provide a debug log for the tesla binding? That way we can see what comes from the server, it seems like the Tesla API sometimes returns null values for things that we don't expect to be nullable

**Comment by phuongpham** [comment]
What's status for this issue?
I see I have same error in the logs:

17:21:20.431 [INFO ] [smarthome.event.ItemStateChangedEvent] - Tesla_EventTimestamp changed from 2019-02-06T17:21:19.654+0100 to 2019-02-06T17:21:19.895+0100
17:21:21.943 [DEBUG] [g.tesla.internal.handler.TeslaHandler] - Invoking: charge_state
17:21:21.945 [DEBUG] [g.tesla.internal.handler.TeslaHandler] - Invoking: climate_state
17:21:22.939 [DEBUG] [g.tesla.internal.handler.TeslaHandler] - Invoking: gui_settings
17:21:23.032 [INFO ] [smarthome.event.ItemStateChangedEvent] - Tesla_ChargeCurrent changed from 0 to 32
17:21:23.064 [ERROR] [internal.items.ItemStateConverterImpl] - A conversion of null was requested:
java.lang.IllegalArgumentException: State must not be null.
	at org.eclipse.smarthome.core.internal.items.ItemStateConverterImpl.convertToAcceptedState(ItemStateConverterImpl.java:52) ~[?:?]
	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.sendUpdate(ProfileCallbackImpl.java:135) ~[?:?]
	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onStateUpdateFromHandler(SystemDefaultProfile.java:54) ~[?:?]
	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$9(CommunicationManager.java:477) ~[?:?]
	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$11(CommunicationManager.java:497) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.handleCallFromHandler(CommunicationManager.java:493) ~[?:?]
	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.stateUpdated(CommunicationManager.java:475) ~[?:?]
	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$1.stateUpdated(ThingManagerImpl.java:167) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:287) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:306) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaHandler.parseAndUpdate(TeslaHandler.java:693) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaHandler$Request.run(TeslaHandler.java:1392) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	at org.openhab.binding.tesla.internal.throttler.QueueChannelThrottler.lambda$0(QueueChannelThrottler.java:45) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
17:21:23.102 [INFO ] [smarthome.event.ItemStateChangedEvent] - Tesla_ChargeCurrent changed from 32 to 0
17:21:23.208 [INFO ] [smarthome.event.ItemStateChangedEvent] - Tesla_EventTimestamp changed from 2019-02-06T17:21:19.895+0100 to 2019-02-06T17:21:22.754+0100

**Comment by cguedel** [comment]
@phuongpham Could you attach a log with TRACE enabled? Sorry, I thought the relevant output was included when using DEBUG, but I'm interested in the response yielded by the tesla backend.

**Comment by phuongpham** [comment]
[openhab.log](https://github.com/openhab/openhab2-addons/files/2838264/openhab.log)
Sure

**Comment by cguedel** [comment]
I see, probably the issue is with the conn_charge_cable value. No idea why that one does not throw that exception for me, as I also have some "<invalid>" and "IEC" values there that were converted to a decimal.

Can you try https://github.com/openhab/openhab2-addons/pull/4824 and report?

**Comment by phuongpham** [comment]
> I see, probably the issue is with the conn_charge_cable value. No idea why that one does not throw that exception for me, as I also have some "" and "IEC" values there that were converted to a decimal.
> 
> Can you try #4824 and report?

Sure
But do you know if this fix this issue: https://github.com/openhab/openhab2-addons/issues/4509

**Comment by cguedel** [comment]
No, that one was fixed a few days ago (so it'll be also in the new jar file). 
Jar file is currently being built, I'll update once available

**Comment by cguedel** [comment]
@phuongpham I think this one should include the changes: https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.tesla/2.5.0-SNAPSHOT/org.openhab.binding.tesla-2.5.0-SNAPSHOT.jar

**Comment by phuongpham** [comment]
> @phuongpham I think this one should include the changes: https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.tesla/2.5.0-SNAPSHOT/org.openhab.binding.tesla-2.5.0-SNAPSHOT.jar

Sorry but I mean if your fix also including the fix that already has been solved

**Comment by cguedel** [comment]
> No, that one was fixed a few days ago (so it'll be also in the new jar file).
So, yes, the jar I linked above contains all the fixes plus the one for this specific problem stated above. Can you please check and report?

**Comment by phuongpham** [comment]
Seems like I still getting the same issue:

18:40:11.841 [TRACE] [g.tesla.internal.handler.TeslaHandler] - The variable/value pair 'charging_state':'"Disconnected"' is successfully processed
18:40:11.845 [ERROR] [internal.items.ItemStateConverterImpl] - A conversion of null was requested:
java.lang.IllegalArgumentException: State must not be null.
        at org.eclipse.smarthome.core.internal.items.ItemStateConverterImpl.convertToAcceptedState(ItemStateConverterImpl.java:52) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.sendUpdate(ProfileCallbackImpl.java:135) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onStateUpdateFromHandler(SystemDefaultProfile.java:54) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$9(CommunicationManager.java:477) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$11(CommunicationManager.java:497) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.handleCallFromHandler(CommunicationManager.java:493) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.stateUpdated(CommunicationManager.java:475) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$1.stateUpdated(ThingManagerImpl.java:167) ~[?:?]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:287) ~[?:?]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:306) ~[?:?]
        at org.openhab.binding.tesla.internal.handler.TeslaHandler.parseAndUpdate(TeslaHandler.java:693) ~[?:?]
        at org.openhab.binding.tesla.internal.handler.TeslaHandler$Request.run(TeslaHandler.java:1392) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
        at org.openhab.binding.tesla.internal.throttler.QueueChannelThrottler.lambda$0(QueueChannelThrottler.java:45) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
18:40:11.851 [INFO ] [smarthome.event.ItemStateChangedEvent] - Tesla_ChargeCurrent changed from 32 to UNDEF
18:40:11.892 [TRACE] [g.tesla.internal.handler.TeslaHandler] - The variable/value pair 'conn_charge_cable':'"<invalid>"' is successfully processed

**Comment by phuongpham** [comment]
@cguedel still no new .jar? it's because of https://github.com/openhab/openhab2-addons/pull/4824 is still pending?

**Comment by phuongpham** [comment]
@cguedel @cweitkamp still nothing new?

**Comment by cweitkamp** [comment]
@phuongpham The PR has been merged. Fix will be available in next snapshot build.

**Comment by phuongpham** [comment]
> @phuongpham The PR has been merged. Fix will be available in next snapshot build.

Great! Thanks for your help guys! I will test it and report back

**Comment by phuongpham** [comment]
@cguedel  ok I have now tested the new jar. The error is now gone from the log. However the Charge cable properties return value: <invalid> 
Maybe the API doesn't return value?

**Comment by cguedel** [comment]
@phuongpham As indicated by the logs you posted, the value <invalid> is sent by the tesla backend. Nothing we can do about that.
