### ISSUE TITLE
[tesla] "IllegalStateException: Expected a boolean but was NUMBER" for seat_heater_left

### ISSUE THREAD

**Issue by phuongpham** [openhab/openhab2-addons#4509]
I have Tesla Model S85 2014 and currently running on 2018.48.12.1 d6999f5
The openHAB is running on 2.4.0 and the binding is installed thru paper UI (Tesla binding 2.4)

I currently see this error: 2018-12-24 11:02:53.550 [ERROR] [b.binding.tesla.handler.TeslaHandler] - An exception occurred while parsing data received from the vehicle: 'java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 460 path $.seat_heater_left'

Similar issue was closed here: https://github.com/openhab/openhab2-addons/issues/3261

But for me it seems like the Tesla API is now back with boolean instead of NUMBER.

**Comment by crystollic** [comment]
Getting the same on Model S P90D same s/w version, although I am sure it was also on previous versions.  Also I think the Tesla API is returning a number but the binding expects a boolean.  I assume a number between 0-3 to reflect the heater setting?

**Comment by kgoderis** [comment]
@kaikreuzer Fixed by https://github.com/openhab/openhab2-addons/pull/4781

**Comment by phuongpham** [comment]
> @kaikreuzer Fixed by #4781
Great!
Maybe stupid question. But where can I download the fixed version?

**Comment by phuongpham** [comment]
Just downloaded the latest snahot from here: https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.tesla/2.5.0-SNAPSHOT/ and I can confirm that the issue is now solved! Thanks

**Comment by jpk8201** [comment]
I have also a Tesla S (2015). I replaced the jar file. Unfortunately I still have the error.
